#! /bin/bash
lineSum=0
sum=0
while read myLine
do
    for i in $myLine
    do
        printf "$i\t"
        lineSum=$(expr $lineSum + $i)
    done
    printf "\nline sum: $lineSum\n"
    sum=$(expr $sum + $lineSum)
    lineSum=0
done < $1
cat -A < $1
printf "sum: $sum\n"