#! /bin/bash
#echo -e "$SHELL\t"
#echo -e "$HOME\t"
cd ~
pwd
ls -pla --color=auto
mkdir dirToRemove
touch myFile
mv myFile dirToRemove
cd dirToRemove
ls -pla --color=auto
touch myFile
cp myFile copyOfMyFile
ls -pla --color=auto
cd ~
ls
rm -rf dirToRemove
ls